import type { Metadata } from "next";
import { Inter, DM_Mono, Archivo } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });
const archivo = Archivo({ subsets: ["latin"] });
const dmmono = DM_Mono({ weight: "500", variable: '--font-mono', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.className} ${dmmono.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
